#!/bin/bash

#NCBI "Welcome to E-utilities for PubMed" Sample Code for Class
#      Exercises"; source:
#  https://dataguide.nlm.nih.gov/classes/intro/samplecode.html


#3. Create a customized version of the Discovery Bar "Results
#   By Year” histogram, comparing two searches
#
esearch -db pubmed -query   \
   "fentanyl abuse" -datetype PDAT   \
   -mindate 1988 -maxdate 2020   | \
efetch -format xml   | \
xtract -pattern PubmedArticle -block PubDate   \
       -element Year MedlineDate   | \
cut -c -4   | \
egrep "[0-9]{4}"   | \
sort-uniq-count-rank    | \
sort -n -t $'\t' -k 2 > fentanyl_abuse.txt

esearch -db pubmed -query   \
   "oxycodone abuse" -datetype PDAT   \
   -mindate 1988 -maxdate 2020   | \
efetch -format xml   | \
xtract -pattern PubmedArticle -block PubDate   \
       -element Year MedlineDate   | \
cut -c -4   | \
egrep "[0-9]{4}"   | \
sort-uniq-count-rank   | \
sort -n -t $'\t' -k 2 > oxycodone_abuse.txt

join -j 2 -o 0,1.1,2.1 -a1 -a2 -e0 -t $'\t'   \
   <(cat fentanyl_abuse.txt)   \
   <(cat oxycodone_abuse.txt)   \
   > abuse_compare.txt

ls *abuse*.txt
tail -n 10 abuse_compare.txt
