#!/bin/bash
#
# Installing NCBI edirect utilities into the current directory ...

INSTALLDIR=`pwd`

echo "Installing NCBI edirect utilities into $INSTALLDIR ..."
echo ""

perl -MNet::FTP -e \
    '$ftp = new Net::FTP("ftp.ncbi.nlm.nih.gov", Passive => 1);
    $ftp->login; $ftp->binary;
    $ftp->get("/entrez/entrezdirect/edirect.tar.gz");'
gunzip -c edirect.tar.gz | tar xf -
rm edirect.tar.gz
# ... correcting a minor mistake in the code as currently distributed
#     (Augusti 27, 2020; reported):
sed -i -e "s/HTTP:Cookies/HTTP::Cookies/" edirect/setup-deps.pl

echo "" >> ~/.profile
echo "# set PATH so it includes the edirect if it exists" >> ~/.profile
echo "if [ -d  $INSTALLDIR/edirect  ] ; then" >> ~/.profile
echo "    PATH=$INSTALLDIR/edirect:$PATH" >> ~/.profile
echo "fi" >> ~/.profile

./edirect/setup.sh
echo ""
echo "One more step:"
echo ""
echo "Execute 'source ~/.profile' to update your PATH variable."
