#!/bin/bash

# Public domain notice for all NCBI EDirect scripts is located at:
# https://www.ncbi.nlm.nih.gov/books/NBK179288/#chapter6.Public_Domain_Notice

# This script is adapted from https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/install-edirect.sh
#  as distributed by NCBI, allowing installation in the current directory.

base="ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect"

# function to fetch a single file, passed as an argument
FetchFile() {

  fl="$1"

  if [ -x "$(command -v curl)" ]
  then
    curl -s "${base}/${fl}" -o "${fl}"
  elif [ -x "$(command -v wget)" ]
  then
    wget "${base}/${fl}"
  else
    echo "Missing curl and wget commands, unable to download EDirect archive" >&2
    exit 1
  fi
}

# edirect folder to be installed in the current directory
echo "edirect will be installed in the current directory: ${PWD}"

# download and extract edirect archive
FetchFile "edirect.tar.gz"
if [ -s "edirect.tar.gz" ]
then
  gunzip -c edirect.tar.gz | tar xf -
  rm edirect.tar.gz
fi
if [ ! -d "edirect" ]
then
  echo "Unable to download EDirect archive" >&2
  exit 1
fi

# remaining executables to be installed within edirect folder
cd edirect

# determine current computer platform
osname=$(uname -s)
cputype=$(uname -m)
case "$osname-$cputype" in
  Linux-x86_64 )           plt=Linux ;;
  Darwin-x86_64 )          plt=Darwin ;;
  Darwin-*arm* )           plt=Silicon ;;
  CYGWIN_NT-* | MINGW*-* ) plt=CYGWIN_NT ;;
  Linux-*arm* )            plt=ARM ;;
esac

# fetch appropriate precompiled versions of xtract, rchive, and transmute
if [ -n "$plt" ]
then
  for exc in xtract rchive transmute
  do
    FetchFile "$exc.$plt.gz"
    gunzip -f "$exc.$plt.gz"
    chmod +x "$exc.$plt"
  done
fi

# offer to edit the PATH variable assignment command in configuration files
echo ""
echo "Entrez Direct has been successfully downloaded and installed."
echo ""
cd ..

todo="
In order to complete the configuration process, please add the following
 lines to your ~/.profile, ~/.bash_profile, or ~/.bashrc shell configuration
 file (or use appropriately modified commands if you are using a non-bash shell):

edirectDIR=${PWD}/edirect
case \":\${PATH:=\$edirectDIR}:\" in
    *:\"\$edirectDIR\":*)  ;;
    *) PATH=\"\$PATH:\$edirectDIR\"  ;;
esac
export PATH=\${PATH}
"

echo "$todo"


case ":$PATH:" in
  *:$HOME/edirect:*)
    ;;
  *)
    echo ""
    echo "To activate EDirect for this terminal session, please execute the following:"
    echo ""
    printf "export PATH=\${PATH}:\${PWD}/edirect\n"
    echo ""
    ;;
esac
