#!/bin/bash
#
# Installing NCBI edirect utilities into the current directory ...

INSTALLDIR=`pwd`

echo "Installing NCBI edirect utilities into $INSTALLDIR ..."
echo ""

perl -MNet::FTP -e \
    '$ftp = new Net::FTP("ftp.ncbi.nlm.nih.gov", Passive => 1);
    $ftp->login; $ftp->binary;
    $ftp->get("/entrez/entrezdirect/edirect.tar.gz");'
gunzip -c edirect.tar.gz | tar xf -
rm edirect.tar.gz

# Adding accessory programs:
#
cd edirect
wget https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/xtract.Linux.gz
gunzip xtract.Linux.gz 
chmod a+x xtract.Linux 

wget https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/transmute.Linux.gz
gunzip -f transmute.Linux.gz 
chmod a+x transmute.Linux 

wget https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/rchive.Linux.gz
gunzip -f rchive.Linux.gz 
chmod a+x rchive.Linux 

# Finishing up:
#
echo "" >> ~/.profile
echo "# set PATH so it includes the edirect if it exists" >> ~/.profile
echo "if [ -d  $INSTALLDIR/edirect  ] ; then" >> ~/.profile
echo "    PATH=$PATH:$INSTALLDIR/edirect" >> ~/.profile
echo "fi" >> ~/.profile

echo ""
echo "One more step:"
echo ""
echo "Execute 'source ~/.profile' to update your PATH variable."
