#!/bin/bash
#

cat $1 | sed -e '$ s/$/\n\n\n/' | sed -e "s/\(^[0-9]\+\. \)/@@@REF@@@\1/; s/$/@@@NL@@@/;" | tr -d '\n' | sed -e "s/@@@REF@@@/\n/g" | tac | sed -e "s/@@@NL@@@/\n/g" > $1_revord
 
echo -e "\n\n"
head -n 40 $1_revord
