#!/bin/bash
#

sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade

sudo apt install gcc make
sudo apt install openssl libssl-dev
sudo apt install zip zlib1g-dev
sudo apt install dos2unix
sudo apt install expat libexpat1-dev
sudo apt install cpanminus
sudo apt install bibutils
sudo apt install xsltproc

sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade

