#!/bin/bash
#

sudo dnf install gcc make
sudo dnf install openssl openssl-libs
sudo dnf install zip libzip
sudo dnf install dos2unix
sudo dnf install expat expat-devel
sudo dnf install cpanminus
sudo dnf install bibutils
sudo dnf install libxslt
